<<<<<<< HEAD
﻿///*
// * In Program.Main , demonstrate: creating a repository instance, adding a new product, retrieving and
//displaying all products, updating a product's price, deleting a product, and using a try-catch for
//database errors.
// */

////help me do the above in the bottom here: 

//using ExamDapperCRUD;
//using System.ComponentModel;

//string connectionString = @"Server=.\SQLEXPRESS;Database=ProductsDB;Trusted_Connection=True;";
//ProductRepository productRepository = new ProductRepository(connectionString);

//Console.WriteLine("product name:");
//var pName = Console.ReadLine();

//Console.WriteLine("Enter price:");
//var pPrice = double.Parse(Console.ReadLine());

//Product product = new Product 
//{
//    Name = pName,
//    Price = pPrice
//};

//var productId = productRepository.AddProduct(product);
//Console.WriteLine($"Product added with ID: {productId}");

//correction:
/*
 * Program.cs - ExamDapperCRUD
 * Demonstrates all CRUD operations using ProductRepository:
 * - Creating a repository instance
 * - Adding a new product
 * - Retrieving and displaying all products
 * - Updating a product's price
 * - Deleting a product
 * - Using try-catch for database errors
 */

using ExamDapperCRUD;

// Connection string pointing to the local SQL Server
// Adjust the server name to match your SQL Server instance
// .\SQLEXPRESS = local SQL Server Express instance
string connectionString = @"Server=.\SQLEXPRESS;Database=ProductsDB;
                             Trusted_Connection=True;
                             TrustServerCertificate=True;";

// Create the repository - pass connection string in (not hard-coded inside)
// This is the abstraction pattern - Program talks to the repository,
// not directly to the database
ProductRepository productRepository = new ProductRepository(connectionString);

// Wrap all operations in try-catch to handle database errors gracefully
// without crashing the application
try
{
    // ── ADD A NEW PRODUCT ─────────────────────────────────────
    Console.WriteLine("=== ADD PRODUCT ===");
    Console.Write("Product name: ");
    // FIX: use ?? string.Empty to handle null safely
    // Console.ReadLine() returns string? (nullable)
    // If user just presses Enter, we default to empty string
    var pName = Console.ReadLine() ?? string.Empty;

    Console.Write("Enter price: ");
    // FIX: use decimal.TryParse instead of double.Parse
    // decimal.TryParse never throws - returns false if invalid
    // double.Parse throws FormatException on bad input like "abc"
    if (!decimal.TryParse(Console.ReadLine(), out decimal pPrice))
    {
        Console.WriteLine("Invalid price entered. Using 0.00");
        pPrice = 0;
    }

    Console.Write("Enter stock quantity: ");
    if (!int.TryParse(Console.ReadLine(), out int pStock))
    {
        Console.WriteLine("Invalid stock entered. Using 0.");
        pStock = 0;
    }

    // Build the Product object to insert
    // Only set the properties we have - Id is auto-generated by DB
    Product newProduct = new Product
    {
        Name = pName,
        Price = pPrice,
        Stock = pStock
    };

    // AddProduct inserts the row and returns the new auto-generated Id
    int productId = productRepository.AddProduct(newProduct);
    Console.WriteLine($"Product added successfully with ID: {productId}\n");


    // ── GET ALL PRODUCTS ──────────────────────────────────────
    Console.WriteLine("=== ALL PRODUCTS ===");
    var allProducts = productRepository.GetAllProducts();

    // Check if any products exist before trying to display them
    if (!allProducts.Any())
    {
        Console.WriteLine("No products found in the database.");
    }
    else
    {
        // Print a simple table header
        Console.WriteLine($"{"ID",-5} {"Name",-20} {"Price",-10} {"Stock",-10}");
        Console.WriteLine(new string('-', 45));

        // Loop through each product and display its details
        foreach (Product p in allProducts)
        {
            // R2 formats price to 2 decimal places e.g. 99.99
            Console.WriteLine($"{p.Id,-5} {p.Name,-20} {p.Price,-10:R2} {p.Stock,-10}");
        }
    }
    Console.WriteLine();


    // ── GET SINGLE PRODUCT BY ID ──────────────────────────────
    Console.WriteLine("=== GET PRODUCT BY ID ===");
    Console.Write("Enter product ID to retrieve: ");

    if (int.TryParse(Console.ReadLine(), out int searchId))
    {
        // GetProductById returns null if not found (QueryFirstOrDefault)
        Product? found = productRepository.GetProductById(searchId);

        if (found != null)
        {
            Console.WriteLine($"Found: ID={found.Id} | Name={found.Name} | " +
                              $"Price=R{found.Price:F2} | Stock={found.Stock}");
        }
        else
        {
            Console.WriteLine($"No product found with ID {searchId}.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── UPDATE A PRODUCT ──────────────────────────────────────
    Console.WriteLine("=== UPDATE PRODUCT ===");
    Console.Write("Enter ID of product to update: ");

    if (int.TryParse(Console.ReadLine(), out int updateId))
    {
        // Fetch the existing product first so we keep unchanged fields
        Product? toUpdate = productRepository.GetProductById(updateId);

        if (toUpdate != null)
        {
            Console.WriteLine($"Current: Name={toUpdate.Name} | " +
                              $"Price=R{toUpdate.Price:F2} | Stock={toUpdate.Stock}");

            Console.Write("New name (press Enter to keep current): ");
            string newName = Console.ReadLine() ?? string.Empty;

            // Only update name if user typed something
            if (!string.IsNullOrWhiteSpace(newName))
                toUpdate.Name = newName;

            Console.Write("New price (press Enter to keep current): ");
            string priceInput = Console.ReadLine() ?? string.Empty;

            // Only update price if user typed a valid decimal
            if (decimal.TryParse(priceInput, out decimal newPrice))
                toUpdate.Price = newPrice;

            Console.Write("New stock (press Enter to keep current): ");
            string stockInput = Console.ReadLine() ?? string.Empty;

            if (int.TryParse(stockInput, out int newStock))
                toUpdate.Stock = newStock;

            // Execute the update - returns true if successful
            bool updated = productRepository.UpdateProduct(toUpdate);

            if (updated)
                Console.WriteLine("Product updated successfully.");
            else
                Console.WriteLine("Update failed - product not found.");
        }
        else
        {
            Console.WriteLine($"No product found with ID {updateId}.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── DELETE A PRODUCT ──────────────────────────────────────
    Console.WriteLine("=== DELETE PRODUCT ===");
    Console.Write("Enter ID of product to delete: ");

    if (int.TryParse(Console.ReadLine(), out int deleteId))
    {
        // Confirm before deleting
        Console.Write($"Are you sure you want to delete product {deleteId}? (Y/N): ");
        string confirm = Console.ReadLine()?.Trim().ToUpper() ?? "N";

        if (confirm == "Y")
        {
            // DeleteProduct only needs the id - not the whole object
            bool deleted = productRepository.DeleteProduct(deleteId);

            if (deleted)
                Console.WriteLine($"Product {deleteId} deleted successfully.");
            else
                Console.WriteLine($"Delete failed - product {deleteId} not found.");
        }
        else
        {
            Console.WriteLine("Delete cancelled.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── FINAL STATE - SHOW ALL REMAINING PRODUCTS ─────────────
    Console.WriteLine("=== REMAINING PRODUCTS ===");
    var remaining = productRepository.GetAllProducts();

    if (!remaining.Any())
    {
        Console.WriteLine("No products remaining.");
    }
    else
    {
        Console.WriteLine($"{"ID",-5} {"Name",-20} {"Price",-10} {"Stock",-10}");
        Console.WriteLine(new string('-', 45));
        foreach (Product p in remaining)
            Console.WriteLine($"{p.Id,-5} {p.Name,-20} {p.Price,-10:F2} {p.Stock,-10}");
    }
}
// Catch any database-related errors
// SqlException covers: connection failures, invalid SQL, constraint violations
catch (Microsoft.Data.SqlClient.SqlException sqlEx)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"\nDatabase error: {sqlEx.Message}");
    Console.ResetColor();
}
// Catch any other unexpected errors
catch (Exception ex)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"\nUnexpected error: {ex.Message}");
    Console.ResetColor();
}

Console.WriteLine("\nPress any key to exit...");
Console.ReadKey();

=======
﻿///*
// * In Program.Main , demonstrate: creating a repository instance, adding a new product, retrieving and
//displaying all products, updating a product's price, deleting a product, and using a try-catch for
//database errors.
// */

////help me do the above in the bottom here: 

//using ExamDapperCRUD;
//using System.ComponentModel;

//string connectionString = @"Server=.\SQLEXPRESS;Database=ProductsDB;Trusted_Connection=True;";
//ProductRepository productRepository = new ProductRepository(connectionString);

//Console.WriteLine("product name:");
//var pName = Console.ReadLine();

//Console.WriteLine("Enter price:");
//var pPrice = double.Parse(Console.ReadLine());

//Product product = new Product 
//{
//    Name = pName,
//    Price = pPrice
//};

//var productId = productRepository.AddProduct(product);
//Console.WriteLine($"Product added with ID: {productId}");

//correction:
/*
 * Program.cs - ExamDapperCRUD
 * Demonstrates all CRUD operations using ProductRepository:
 * - Creating a repository instance
 * - Adding a new product
 * - Retrieving and displaying all products
 * - Updating a product's price
 * - Deleting a product
 * - Using try-catch for database errors
 */

using ExamDapperCRUD;

// Connection string pointing to the local SQL Server
// Adjust the server name to match your SQL Server instance
// .\SQLEXPRESS = local SQL Server Express instance
string connectionString = @"Server=.\SQLEXPRESS;Database=ProductsDB;
                             Trusted_Connection=True;
                             TrustServerCertificate=True;";

// Create the repository - pass connection string in (not hard-coded inside)
// This is the abstraction pattern - Program talks to the repository,
// not directly to the database
ProductRepository productRepository = new ProductRepository(connectionString);

// Wrap all operations in try-catch to handle database errors gracefully
// without crashing the application
try
{
    // ── ADD A NEW PRODUCT ─────────────────────────────────────
    Console.WriteLine("=== ADD PRODUCT ===");
    Console.Write("Product name: ");
    // FIX: use ?? string.Empty to handle null safely
    // Console.ReadLine() returns string? (nullable)
    // If user just presses Enter, we default to empty string
    var pName = Console.ReadLine() ?? string.Empty;

    Console.Write("Enter price: ");
    // FIX: use decimal.TryParse instead of double.Parse
    // decimal.TryParse never throws - returns false if invalid
    // double.Parse throws FormatException on bad input like "abc"
    if (!decimal.TryParse(Console.ReadLine(), out decimal pPrice))
    {
        Console.WriteLine("Invalid price entered. Using 0.00");
        pPrice = 0;
    }

    Console.Write("Enter stock quantity: ");
    if (!int.TryParse(Console.ReadLine(), out int pStock))
    {
        Console.WriteLine("Invalid stock entered. Using 0.");
        pStock = 0;
    }

    // Build the Product object to insert
    // Only set the properties we have - Id is auto-generated by DB
    Product newProduct = new Product
    {
        Name = pName,
        Price = pPrice,
        Stock = pStock
    };

    // AddProduct inserts the row and returns the new auto-generated Id
    int productId = productRepository.AddProduct(newProduct);
    Console.WriteLine($"Product added successfully with ID: {productId}\n");


    // ── GET ALL PRODUCTS ──────────────────────────────────────
    Console.WriteLine("=== ALL PRODUCTS ===");
    var allProducts = productRepository.GetAllProducts();

    // Check if any products exist before trying to display them
    if (!allProducts.Any())
    {
        Console.WriteLine("No products found in the database.");
    }
    else
    {
        // Print a simple table header
        Console.WriteLine($"{"ID",-5} {"Name",-20} {"Price",-10} {"Stock",-10}");
        Console.WriteLine(new string('-', 45));

        // Loop through each product and display its details
        foreach (Product p in allProducts)
        {
            // R2 formats price to 2 decimal places e.g. 99.99
            Console.WriteLine($"{p.Id,-5} {p.Name,-20} {p.Price,-10:R2} {p.Stock,-10}");
        }
    }
    Console.WriteLine();


    // ── GET SINGLE PRODUCT BY ID ──────────────────────────────
    Console.WriteLine("=== GET PRODUCT BY ID ===");
    Console.Write("Enter product ID to retrieve: ");

    if (int.TryParse(Console.ReadLine(), out int searchId))
    {
        // GetProductById returns null if not found (QueryFirstOrDefault)
        Product? found = productRepository.GetProductById(searchId);

        if (found != null)
        {
            Console.WriteLine($"Found: ID={found.Id} | Name={found.Name} | " +
                              $"Price=R{found.Price:F2} | Stock={found.Stock}");
        }
        else
        {
            Console.WriteLine($"No product found with ID {searchId}.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── UPDATE A PRODUCT ──────────────────────────────────────
    Console.WriteLine("=== UPDATE PRODUCT ===");
    Console.Write("Enter ID of product to update: ");

    if (int.TryParse(Console.ReadLine(), out int updateId))
    {
        // Fetch the existing product first so we keep unchanged fields
        Product? toUpdate = productRepository.GetProductById(updateId);

        if (toUpdate != null)
        {
            Console.WriteLine($"Current: Name={toUpdate.Name} | " +
                              $"Price=R{toUpdate.Price:F2} | Stock={toUpdate.Stock}");

            Console.Write("New name (press Enter to keep current): ");
            string newName = Console.ReadLine() ?? string.Empty;

            // Only update name if user typed something
            if (!string.IsNullOrWhiteSpace(newName))
                toUpdate.Name = newName;

            Console.Write("New price (press Enter to keep current): ");
            string priceInput = Console.ReadLine() ?? string.Empty;

            // Only update price if user typed a valid decimal
            if (decimal.TryParse(priceInput, out decimal newPrice))
                toUpdate.Price = newPrice;

            Console.Write("New stock (press Enter to keep current): ");
            string stockInput = Console.ReadLine() ?? string.Empty;

            if (int.TryParse(stockInput, out int newStock))
                toUpdate.Stock = newStock;

            // Execute the update - returns true if successful
            bool updated = productRepository.UpdateProduct(toUpdate);

            if (updated)
                Console.WriteLine("Product updated successfully.");
            else
                Console.WriteLine("Update failed - product not found.");
        }
        else
        {
            Console.WriteLine($"No product found with ID {updateId}.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── DELETE A PRODUCT ──────────────────────────────────────
    Console.WriteLine("=== DELETE PRODUCT ===");
    Console.Write("Enter ID of product to delete: ");

    if (int.TryParse(Console.ReadLine(), out int deleteId))
    {
        // Confirm before deleting
        Console.Write($"Are you sure you want to delete product {deleteId}? (Y/N): ");
        string confirm = Console.ReadLine()?.Trim().ToUpper() ?? "N";

        if (confirm == "Y")
        {
            // DeleteProduct only needs the id - not the whole object
            bool deleted = productRepository.DeleteProduct(deleteId);

            if (deleted)
                Console.WriteLine($"Product {deleteId} deleted successfully.");
            else
                Console.WriteLine($"Delete failed - product {deleteId} not found.");
        }
        else
        {
            Console.WriteLine("Delete cancelled.");
        }
    }
    else
    {
        Console.WriteLine("Invalid ID entered.");
    }
    Console.WriteLine();


    // ── FINAL STATE - SHOW ALL REMAINING PRODUCTS ─────────────
    Console.WriteLine("=== REMAINING PRODUCTS ===");
    var remaining = productRepository.GetAllProducts();

    if (!remaining.Any())
    {
        Console.WriteLine("No products remaining.");
    }
    else
    {
        Console.WriteLine($"{"ID",-5} {"Name",-20} {"Price",-10} {"Stock",-10}");
        Console.WriteLine(new string('-', 45));
        foreach (Product p in remaining)
            Console.WriteLine($"{p.Id,-5} {p.Name,-20} {p.Price,-10:F2} {p.Stock,-10}");
    }
}
// Catch any database-related errors
// SqlException covers: connection failures, invalid SQL, constraint violations
catch (Microsoft.Data.SqlClient.SqlException sqlEx)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"\nDatabase error: {sqlEx.Message}");
    Console.ResetColor();
}
// Catch any other unexpected errors
catch (Exception ex)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"\nUnexpected error: {ex.Message}");
    Console.ResetColor();
}

Console.WriteLine("\nPress any key to exit...");
Console.ReadKey();

>>>>>>> f1fd9259c06725f9a30786509326a6e923171712
