<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-mvc_BloggingPlatform-31b8822b-4f57-4388-a15b-3f7c9be67341</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.19" />
  </ItemGroup>

</Project>
